version: "3.9"

services:
  database:
    container_name: CrudProducts_database
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres

  # redis:
  #     container_name: redis
  #     image: redis:alpine
  #     ports:
  #         - 6379:6379
volumes:
  pgdata:
    driver: local

